### ISSUE TITLE
Apply Leave:  Error Message "No Message Available" is displayed when the employee try to submit the leaves is not under his entitlement. 

### ISSUE THREAD

**Issue by laichiun** [shahrul91/csileavemanagementsystem#150]
Module: Apply Leave

Issues: Error Message "No Message Available" is displayed when the employee try to submit the leaves is not under his entitlement. 

Expected: Error message display should be more specific related to the issues. 

![image](https://user-images.githubusercontent.com/48428855/54255646-e837f080-4593-11e9-8777-43d57eb3fa70.png)

![image](https://user-images.githubusercontent.com/48428855/54255724-28976e80-4594-11e9-99ad-e7ff0881fc13.png)
![image](https://user-images.githubusercontent.com/48428855/54255744-3baa3e80-4594-11e9-89c3-e00b2a2f9b6d.png)

**Comment by chaikp** [comment]
Fixed - pending deploying to live server

**Comment by chaikp** [comment]
Deployed to live server. The error display when user apply leave without leave entitlement : 

![image](https://user-images.githubusercontent.com/46370369/54508162-d8e3e900-497f-11e9-888c-88b441515e6f.png)

**Comment by syazanajaafar** [comment]
Retest complete and Pass. Hence will close the defect.

Please refer to the attachment below for evidence.

![Not Entitle Leave Msg](https://user-images.githubusercontent.com/48428869/54519274-17d66680-49a1-11e9-8b92-f64aea63a4d6.PNG)
