### ISSUE TITLE
View my Leave History: Suggest to display "Approval Name" Instead of "Approval ID" 

### ISSUE THREAD

**Issue by laichiun** [shahrul91/csileavemanagementsystem#151]
Module: View My Leave History

Issues/Suggestion: Suggest to display "Approval Name" instead of "Approval ID". 

![image](https://user-images.githubusercontent.com/48428855/54256958-acebf080-4598-11e9-9224-c787866512af.png)

**Comment by netkiko** [comment]
Done. The new update (not yet uploaded in the server) displays Approver Name and Approver ID.

**Comment by syazanajaafar** [comment]
The new update already displays in live server as below:

![Approver_Name ID Display](https://user-images.githubusercontent.com/48428869/54795975-426a3d00-4c89-11e9-99f9-47f85e530bec.PNG)
