### ISSUE TITLE
HR Dashboard - Leave Entitlements - Available Leave, Taken Leave, and Balance Leave

### ISSUE THREAD

**Issue by syazanajaafar** [shahrul91/csileavemanagementsystem#154]
**Module(s):**
HR Dashboard - Leave Entitlements

**Issues / Suggestions:**
1. Available Leave 
Suggest to automatically calculate for sum of 'Carried Forward' leave and 'Entitlement' leave instead of manually fill up and the textbox should be disable (View purpose only).

2. Taken Leave
Suggest for Taken Leave should not manually fill up but directly fetch the data from database so it should be synchronized with Employee Leave History. The textbox also should be disable (view purpose only)
 
3. Balance Leave
Suggest to automatically calculate for Balance Leave instead of manually fill up and the textbox should be disable (view purpose only).  

**Expected:**
N/A

**Actual Results:**
N/A

**Comment by shahrul91** [comment]
We will include this into phase 2 project.

**Comment by shahrul91** [comment]
Pending deploy to Live Server.

**Comment by syazanajaafar** [comment]
As discussed with the team, agreed to only automatically calculate / fetch data for Balance Leave and Taken Leave.
Re-test and working as expected per discussion.

![Leave Entitlement](https://user-images.githubusercontent.com/48428869/55304317-76a9de80-547d-11e9-9846-3c9eb12a446b.PNG)
