### ISSUE TITLE
HR Dashboard - Employee Profile : Validation is showing PASSED but the Mobile Number is incomplete display after upload 

### ISSUE THREAD

**Issue by laichiun** [shahrul91/csileavemanagementsystem#155]
**Modules:** HR Dashboard - Upload Employee Profile

**Issues:**
Validation is showing PASSED but the Mobile Number is incomplete displayed where the initial zero and dash are missing after upload. 
Example: 
Value in the Employee Profile upload template : 012-3455666
Value display in the Upload employee Profile page after upload: 123455666

![image](https://user-images.githubusercontent.com/48428855/54260504-10c7e680-45a4-11e9-802c-0fea79a34d8a.png)

![image](https://user-images.githubusercontent.com/48428855/54260570-3e149480-45a4-11e9-87f1-cbe5686f1a0d.png)

**Comment by netkiko** [comment]
Setting the Format of "MobileNo" column in Excel Template to **Text** will fix this issue. To do it, just right-click on Column **K** on the template, select Format Cells…, then select Text Category in the Format Cells dialog box.

**Comment by chaikp** [comment]
Template updated. please retest, @syazanajaafar

**Comment by laichiun** [comment]
25 March - Restest Passed

Mobile number is updated correctly in the Upload employee Profile page.

![image](https://user-images.githubusercontent.com/48428855/54890784-d9333580-4ee5-11e9-87c5-1bd12836409d.png)
![image](https://user-images.githubusercontent.com/48428855/54890805-eea85f80-4ee5-11e9-9915-02ca54b42dd5.png)
![image](https://user-images.githubusercontent.com/48428855/54890842-24e5df00-4ee6-11e9-82c9-fd1301796ca6.png)
