### ISSUE TITLE
HR Dashboard-Upload Employee Profiles: Error message display when click on the YES

### ISSUE THREAD

**Issue by laichiun** [shahrul91/csileavemanagementsystem#156]
**Modules:** HR Dashboard- Upload Employee Profiles
**Issues:** Error message display when click on the "YES" button to save the new upload employee profiles record. 

![image](https://user-images.githubusercontent.com/48428855/54261242-45d53880-45a6-11e9-9ca0-42296715b579.png)

![image](https://user-images.githubusercontent.com/48428855/54261268-54235480-45a6-11e9-90a7-5afbc4a2b373.png)

![image](https://user-images.githubusercontent.com/48428855/54261284-5e455300-45a6-11e9-959c-a2c8bde2f92b.png)

**Comment by shahrul91** [comment]
This is not bug/defect. The roles in translate items used wrong format. It has been updated by @netkiko
