### ISSUE TITLE
InActive Translate Item appeared in Add Employee Page for Business Unit and Department ID

### ISSUE THREAD

**Issue by syazanajaafar** [shahrul91/csileavemanagementsystem#158]
**Module:**
1. Translate Item
2. HR Dashboard --> Employee Profiles --> +Add Employee

**Issues:**
Inactive Translate Item still appeared in Add Employee page for business unit and department id

**Expected:**
Inactive Translate Item of business unit and department ID should not appeared in Add Employee page.

**Attachment:**

**1. Inactive Business Unit**

![InActive Translate Item_BU](https://user-images.githubusercontent.com/48428869/54326717-520ed380-4642-11e9-8462-2f5d45f92265.PNG)

![Add Employee_InActive BU](https://user-images.githubusercontent.com/48428869/54326736-69e65780-4642-11e9-84f1-ff580e825fd7.PNG)

**2. Inactive Department ID**

![InActive Translate Item_DeptID](https://user-images.githubusercontent.com/48428869/54326763-82ef0880-4642-11e9-97c0-de0cddb5622d.PNG)

![Add Employee_InActive DeptID](https://user-images.githubusercontent.com/48428869/54326786-a2863100-4642-11e9-8b90-ad53ab29dd50.PNG)

**Comment by chaikp** [comment]
Looking into this - along with another backend change (database: retrieving data from Translated Item table instead of Department and Business Unit table)

**Comment by syazanajaafar** [comment]
Question:
if the Translate Item (Eg: Business Unit) being update to Inactive status. Is there any validation to check in the employee profile that attached to the specific Translate Item?

**Comment by chaikp** [comment]
> Question:
> if the Translate Item (Eg: Business Unit) being update to Inactive status. Is there any validation to check in the employee profile that attached to the specific Translate Item?

No validation as of now. 
We did notice an issue when a Business Unit (or Department, etc..) is set to inactive, employee profile with the impacted Business Unit is not displayed in HR Employee Profiles dashboard.

We are working to add the validation now - the Translate Item cannot be set to inactive if there's employee still referencing the value.

**Comment by chaikp** [comment]
Code fix is deployed to live server. Inactive Translate item will no longer be available in drop down selection.

Also added validation - if a Translate Item is being used / referenced by Employee Profile, display following message and do not allow deactivation.
![image](https://user-images.githubusercontent.com/46370369/54508269-56a7f480-4980-11e9-93ad-4df58d7b294c.png)

Translated Items that will be validated are:
1. Business Unit
2. Department ID
3. Gender
4. Marriage Status

**Comment by syazanajaafar** [comment]
Another suggestions for @chaikp @shahrul91 
when editing the Translate Item that has been used / reference by employee Profile, instead of prompt 'Submit Confirmation' message box (as below) then only prompt validation message.
Why not just directly prompt the validation message box?

![Submit Confirmation](https://user-images.githubusercontent.com/48428869/54518010-2e2ef300-499e-11e9-89df-fd40d002e07c.PNG)

**Comment by chaikp** [comment]
Its the sequencing of Validation and Submit Confirmation - the validation happens after user confirms they want to make the change.

It is possible to sequence it differently: perform the validation, then ask for confirmation only if pass validation.

Will look into this change.

**Comment by chaikp** [comment]
@syazanajaafar suggestion has been implemented and deploy. ready for review / retest

**Comment by syazanajaafar** [comment]
Retest complete and pass. The validation working as expected. Hence, will close the defect.

![Defect 158_Fixed](https://user-images.githubusercontent.com/48428869/54730754-8ac02700-4bc5-11e9-8fb3-37c463ac7291.PNG)
