### ISSUE TITLE
HR Dashboard - Leave Entitlement: Leave Entitlement Page showing "No Data Available" after delete one record in Leave Categories.

### ISSUE THREAD

**Issue by laichiun** [shahrul91/csileavemanagementsystem#160]
**Module:** HR Dashboard - Leave Entitlement

**Issues:** After delete one of the record in the Leave Categories, issues found in the Leave Entitlement page, records are unable to load and showing "No Data Available".

![image](https://user-images.githubusercontent.com/48428855/54333530-c4d97800-465d-11e9-8098-77ebfdf4a16f.png)

**Comment by shahrul91** [comment]
We will remove the delete button for the 1st phase. In the 2nd phase we will add advance features.

**Comment by chaikp** [comment]
Completed the Phase 1 fix - removing the delete function for the mean time.

pending deployment

**Comment by chaikp** [comment]
Changes deployed. ready for retest

**Comment by syazanajaafar** [comment]
Retest successfully completed. Delete funtion has been removed. Hence, will close the defect.


 
![Defect 160_Fixed](https://user-images.githubusercontent.com/48428869/54730357-711de000-4bc3-11e9-83ed-c6aa334a253b.PNG)
