### ISSUE TITLE
Modules: HR Dashboard - Leaves Catogories - Add Leave Catogory: No validation on the Leave Code input if user enter more than 2 digits. 

### ISSUE THREAD

**Issue by laichiun** [shahrul91/csileavemanagementsystem#161]
**Modules:** HR Dashboard - Leaves Catogories - Add Leave Catogory

**Issues**: No validation on the Leave Code input if user enter more than 2 digits. The record is not displayed in Leaves Categories after click on the Save and Confirm button. 

**Suggestion:** Can we have success message box if the catogory is added successfully?

![image](https://user-images.githubusercontent.com/48428855/54337451-efc9c900-4669-11e9-8d2b-a836f3449895.png)

![image](https://user-images.githubusercontent.com/48428855/54337502-0f60f180-466a-11e9-8021-1a7825d5dc6d.png)

![image](https://user-images.githubusercontent.com/48428855/54337544-2b649300-466a-11e9-9ce5-6b8ef5731c74.png)

**Comment by acapawn7** [comment]
Added validation while entering Leave Code value, preventing users from entering more than 3 characters.

Pending code review and deployment.

**Comment by acapawn7** [comment]
Only max 3 characters are accepted in Leave Code input.

![image](https://user-images.githubusercontent.com/46367351/54517551-f96e6c00-499c-11e9-9853-fa7ec077b6c1.png)


Success message box added after the Confirm button.
![image](https://user-images.githubusercontent.com/46367351/54517662-46524280-499d-11e9-9668-3c8ffc6c5d64.png)

**Comment by acapawn7** [comment]
Please retest and revert in case of any issue.

**Comment by syazanajaafar** [comment]
Hi @acapawn7,

I did notice some different behaviour in 'Leave Entitlement' when tried to add Leave Category on each different browsers (IE, Chrome, Firefox).  Should it behave this way for each different browser? 
Details attached below.

However the validation is working fine where the 'Save' button is disable when entering non required value.

**Internet Explorer**

![IE_Add Leave Category_Leave Entitlement](https://user-images.githubusercontent.com/48428869/54595857-71f12d80-4a6e-11e9-968e-3e8545c1453d.PNG)


**Chrome**

**Note : Unable to type in except for numeric value

![Chrome_Add Leave Category_Leave Entitlement](https://user-images.githubusercontent.com/48428869/54595884-803f4980-4a6e-11e9-8c95-329aa500c86b.PNG)

**Firefox**

![FireFox_Add Leave Category_Leave Entitlement](https://user-images.githubusercontent.com/48428869/54595900-8cc3a200-4a6e-11e9-884a-df108ff36d74.PNG)

**Comment by acapawn7** [comment]
Your observation is correct.

Currently Firefox and IE browsers do not restrict users from entering non-numerical values, where the code for "<input> element with type number" is being used.

However both browsers will still validate the inputs upon submitting the form (where the Save button is disabled for non-numerical values).

Please pitch in if you guys have any opinion. @chaikp @netkiko @shahrul91

**Comment by syazanajaafar** [comment]
Hi @acapawn7,

Thanks for the clarification. Since this behaviour comes from the browsers so I assume it should be fine as long the validation is working.

Retest for defect #161 is success and validation is working. Hence, I will close the defect.
