### ISSUE TITLE
An Error message is prompt when click 'Upload Entitlements' button.

### ISSUE THREAD

**Issue by syazanajaafar** [shahrul91/csileavemanagementsystem#162]
**Module:** 
HR Dashboard --> Leave Entitlement

**Issue:**
An Error message is prompt when click 'Upload Entitlements' button.

**Attachment:**

![Upload Enttilements_Error Msg](https://user-images.githubusercontent.com/48428869/54337992-8f3b8b80-466b-11e9-89d9-1985cfec56d3.PNG)

**Comment by shahrul91** [comment]
This is the same issue as  #160
