### ISSUE TITLE
Pending approve leave update in Taken Leave

### ISSUE THREAD

**Issue by syazanajaafar** [shahrul91/csileavemanagementsystem#163]
**Module:**
My Leave History, My Leave Details

**Questions:**
Why for Pending approve of Annual Leave in Leave History it will update in Taken Leave in Leave Details,
but for Pending approve of other Leave Categories it didn't update in Taken Leave in Leave Details?

Please refer attachments for more details.

**Attachment(s):**

**1. Annual Leave**

![AL History_Pending-Approved](https://user-images.githubusercontent.com/48428869/54406362-cc0f8d00-4714-11e9-93fa-47808ae2eb95.PNG)

![AL Details-Taken Leave](https://user-images.githubusercontent.com/48428869/54406370-d762b880-4714-11e9-8446-34dcc0978acc.PNG)

**2. Compassionate Leave**

![CompLv History_Pending-Approved](https://user-images.githubusercontent.com/48428869/54406400-f2cdc380-4714-11e9-8cc4-b2e46cc48ac0.PNG)

![CompLv Details-Taken Leave](https://user-images.githubusercontent.com/48428869/54406407-fbbe9500-4714-11e9-9896-eb91235c0916.PNG)

**3. Emergency Leave**

![EL History_Pending-Approved](https://user-images.githubusercontent.com/48428869/54406412-04af6680-4715-11e9-898f-388cc0285ca0.PNG)

![EL Details-Taken Leave](https://user-images.githubusercontent.com/48428869/54406420-15f87300-4715-11e9-8c58-72eb4b0290d9.PNG)

**Comment by chaikp** [comment]
Hi @syazanajaafar, I have ran some tests, the Taken Leave only reflects approved leave for all leave category. 

I am not able to duplicated the issue above. Do you still have the employee name / ID for this test case? Maybe there's other factors involved for the mismatch.

**Comment by syazanajaafar** [comment]
Hi @chaikp,

Details of the employee as below:

Email : lily@chinasofti.com
Employee ID : E000000932

![Lily Details](https://user-images.githubusercontent.com/48428869/54905363-cdfafc80-4f1b-11e9-8ae5-c56ea788201b.PNG)

**Comment by chaikp** [comment]
As per discussed on Slacks, this can either be :

1. an issue with data import when we setup the DB; or
2. Lily's Taken Leave was edited on Leave Entitlement page

What we have in Leave Entitlement functions now :

1. If admin manually changed the Leave Taken on Leave Entitlement, we do not check the actual amount of leave applied and approved in database
2. Any new leave that are approved will deduct base on the Leave Taken from Leave Entitlement, we do not recount the total number of leave approved during leave approval
3. We do not check if Leave Taken and Leave Balance adds up to Leave Available

**Comment by syazanajaafar** [comment]
Solutions for this issue has been rectified. 
Please Refer to #154.
