### ISSUE TITLE
Inappropriate Message error when Employee ID more than required max characters

### ISSUE THREAD

**Issue by syazanajaafar** [shahrul91/csileavemanagementsystem#177]
**Module:**
HR Dashboard --> Employee Profile --> Add Employee Profile

**Issue(s):**
Inappropriate Message error when fill in Employee ID more than 10 characters

**Expected:**
Should prompt appropriate validation error message to notify users when they fill in the Employee ID more than required maximum characters.

**Attachment:**

![Add Employee_Emp ID](https://user-images.githubusercontent.com/48428869/54732985-ec868e00-4bd1-11e9-9c79-98b5ef9c49b5.PNG)

![Add Employee_Error](https://user-images.githubusercontent.com/48428869/54733004-0b852000-4bd2-11e9-9c55-32bc5381a043.PNG)

**Comment by acapawn7** [comment]
Fix has been applied in pull request #194, where user cannot input more than 10 characters.

Tested on most browsers.

**Comment by laichiun** [comment]
29 March- Retest.
Employee ID input length only allow to enter 10 characters

![image](https://user-images.githubusercontent.com/48428855/55202192-638ada80-5201-11e9-83b9-4e987ccfefe9.png)
