### ISSUE TITLE
Inappropriate Message error when Employee Name more than required max characters

### ISSUE THREAD

**Issue by syazanajaafar** [shahrul91/csileavemanagementsystem#178]
**Module:**
HR Dashboard --> Employee Profile --> Add Employee Profile 

**Issues:**
Inappropriate Message error when fill in Employee Name more than 30 characters

**Expected:**
Should prompt appropriate validation error message to notify users when they fill in the Employee Name more than required maximum characters.

**Attachment:**

![Add Employee_Emp Name](https://user-images.githubusercontent.com/48428869/54733770-75072d80-4bd6-11e9-8814-1378008d9ab3.PNG)

![Add Employee_Emp Name Error Msg](https://user-images.githubusercontent.com/48428869/54733775-7afd0e80-4bd6-11e9-892b-b4004c336aa2.PNG)

**Comment by acapawn7** [comment]
Fix has been applied in pull request #194, where user cannot input more than 80 characters.

Tested on most browsers.

**Comment by laichiun** [comment]
29 March - Retest Passed
Employee name input length only allowed enter max 80 characters.  

![image](https://user-images.githubusercontent.com/48428855/55202278-bd8ba000-5201-11e9-8595-42b7584b1630.png)

![image](https://user-images.githubusercontent.com/48428855/55202337-f62b7980-5201-11e9-8151-22131df6b78c.png)
