### ISSUE TITLE
Inappropriate Message error when Business Email more than required maximum characters

### ISSUE THREAD

**Issue by syazanajaafar** [shahrul91/csileavemanagementsystem#179]
**Module:**
HR Dashboard --> Employee Profile --> Add Employee Profile 

**Issues:**
Inappropriate Message error when fill in Business Email more than 30 characters

**Expected:**
Should prompt appropriate validation error message to notify users when they fill in the Business Email more than required maximum characters.

**Attachment:**
![Add Employee_Email](https://user-images.githubusercontent.com/48428869/54733865-ffe82800-4bd6-11e9-8208-a56ab7c56b2e.PNG)

![Add Employee_Email Error Msg](https://user-images.githubusercontent.com/48428869/54733874-06769f80-4bd7-11e9-8c24-874a3867c506.PNG)

**Comment by acapawn7** [comment]
Fix has been applied in pull request #194, where user cannot input more than 30 characters.

Tested on most browsers.

**Comment by laichiun** [comment]
29 March - Retest Passed
Business email input length only allowed to enter max 30 characters. 
![image](https://user-images.githubusercontent.com/48428855/55202408-40145f80-5202-11e9-80a7-5d6ffe73ac6d.png)
![image](https://user-images.githubusercontent.com/48428855/55202422-51f60280-5202-11e9-9d61-6b49a85993de.png)
