### ISSUE TITLE
Inappropriate Message error when NRIC/Pasport No more than required maximum characters

### ISSUE THREAD

**Issue by syazanajaafar** [shahrul91/csileavemanagementsystem#180]
**Module:**
HR Dashboard --> Employee Profile --> Add Employee Profile 

**Issues:**
Inappropriate Message error when fill in NRIC/Pasport No more than 14 characters/digit

**Expected:**
Should prompt appropriate validation error message to notify users when they fill in the NRIC/Pasport No more than required maximum characters.

**Attachment:**

![Add Employee_IC-Pasport](https://user-images.githubusercontent.com/48428869/54733984-cb28a080-4bd7-11e9-8b60-044ff0c85bc9.PNG)

![Add Employee_IC-Pasport Error Msg](https://user-images.githubusercontent.com/48428869/54734022-f9a67b80-4bd7-11e9-9234-83fa4fa8c666.PNG)

**Comment by acapawn7** [comment]
Fix has been applied in pull request #194, where user cannot input more than 14 characters.

Tested on most browsers.

**Comment by laichiun** [comment]
29 March - Defect retest pass
NRIC/Passport input box only accept max 14 characters. 

![image](https://user-images.githubusercontent.com/48428855/55202500-a1d4c980-5202-11e9-9df3-499dcbdfc2d5.png)
