### ISSUE TITLE
Inappropriate Message error when Marriage Count more than required maximum characters

### ISSUE THREAD

**Issue by syazanajaafar** [shahrul91/csileavemanagementsystem#181]
**Module:**
HR Dashboard --> Employee Profile --> Add Employee Profile 

**Issues:**
Inappropriate Message error when fill in Marriage Count more than 2 digit

**Expected:**
Should prompt appropriate validation error message to notify users when they fill in the Marriage Count more than required maximum characters.

**Attachment:**

![Add Employee_MarriageCount](https://user-images.githubusercontent.com/48428869/54734239-30c95c80-4bd9-11e9-8350-f9143f5b8ebe.PNG)

![Add Employee_MarriageCount Error Msg](https://user-images.githubusercontent.com/48428869/54734242-3757d400-4bd9-11e9-95f2-c85bcac28822.PNG)

**Comment by acapawn7** [comment]
Fix has been applied in pull request #194, where user cannot input more than 2 digits and must be  numeric value only.

Tested on most browsers.

**Comment by laichiun** [comment]
29 March - Defect Retest
Marriage count input length only accept max 2 digits and numeric value only.

![image](https://user-images.githubusercontent.com/48428855/55202561-dfd1ed80-5202-11e9-9316-f9ddfc391ac1.png)
