### ISSUE TITLE
Inappropriate Message error when Total Children more than required maximum characters

### ISSUE THREAD

**Issue by syazanajaafar** [shahrul91/csileavemanagementsystem#182]
**Module:**
HR Dashboard --> Employee Profile --> Add Employee Profile 

**Issues:**
Inappropriate Message error when fill in Total Children more than 2 digit

**Expected:**
Should prompt appropriate validation error message to notify users when they fill in the Marriage Count more than required maximum characters.

**Attachment:**

![Add Employee_Total Children](https://user-images.githubusercontent.com/48428869/54734427-5d31a880-4bda-11e9-997c-96698b1d7c77.PNG)

![Add Employee_Total Children Error Msg](https://user-images.githubusercontent.com/48428869/54734435-66bb1080-4bda-11e9-97c7-1246577bcc3d.PNG)

**Comment by acapawn7** [comment]
Fix has been applied in pull request #194, where user cannot input more than 2 digits and must be numeric value only.

Tested on most browsers.

**Comment by laichiun** [comment]
29 March - Retest Passed
Total Children input length only accept 2 digits and numeric value only. 

![image](https://user-images.githubusercontent.com/48428855/55202620-14de4000-5203-11e9-8735-429b100607ad.png)
