### ISSUE TITLE
Inappropriate Message error when Mobile No more than required maximum characters

### ISSUE THREAD

**Issue by syazanajaafar** [shahrul91/csileavemanagementsystem#183]
**Module:**
HR Dashboard --> Employee Profile --> Add Employee Profile 

**Issues:**
Inappropriate Message error when fill in Mobile No more than 15 digit

**Expected:**
Should prompt appropriate validation error message to notify users when they fill in the Mobile No more than required maximum characters.

**Attachment:**

![Add Employee_MobileNo](https://user-images.githubusercontent.com/48428869/54734556-50618480-4bdb-11e9-94c8-44b4fb375811.PNG)

![Add Employee_MobileNo Error Msg](https://user-images.githubusercontent.com/48428869/54734558-56576580-4bdb-11e9-836f-c7952136e5d5.PNG)

**Comment by laichiun** [comment]
29 March - Retest Passed

Mobile No input length only accept max 15 characters. 

![image](https://user-images.githubusercontent.com/48428855/55202664-4c4cec80-5203-11e9-8a11-76f58422305a.png)

![image](https://user-images.githubusercontent.com/48428855/55202693-6edf0580-5203-11e9-9887-7c4cc24aba67.png)

![image](https://user-images.githubusercontent.com/48428855/55202752-b06fb080-5203-11e9-9d4c-c9871c403686.png)
