### ISSUE TITLE
After adding new public holiday, React Table is not updating

### ISSUE THREAD

**Issue by chaikp** [shahrul91/csileavemanagementsystem#186]
Before adding 
![image](https://user-images.githubusercontent.com/46370369/54889906-d6364600-4ee1-11e9-88aa-567b05c3b94c.png)

Add new public holiday
![image](https://user-images.githubusercontent.com/46370369/54889941-fb2ab900-4ee1-11e9-9b9a-6c4660bf4b12.png)

Redirect to Public Holiday table - new holiday is not shown
![image](https://user-images.githubusercontent.com/46370369/54889952-07af1180-4ee2-11e9-9637-f01e53c3bdf3.png)

Refresh / navigate to Public Holiday manually
![image](https://user-images.githubusercontent.com/46370369/54889985-404eeb00-4ee2-11e9-93a6-b21a2fab6f37.png)

**Comment by chaikp** [comment]
Bug resolved on development environment. Pending deployment

**Comment by syazanajaafar** [comment]
Delete function is encounter same issue where table is not updated directly after delete which need to Refresh the page or Navigate manually.

**Comment by syazanajaafar** [comment]
Retest and working as expected for both Adding and Delete function in Public Holiday Page.
Hence, will close the defect.
