### ISSUE TITLE
IE browser not able to render whole pages completely (blank displays)

### ISSUE THREAD

**Issue by acapawn7** [shahrul91/csileavemanagementsystem#187]
**Internet Explorer (IE)** browser is not able to render the whole pages and display as blank.
However, it is working fine on **Microsoft Edge** browser.

**On local:**
![image](https://user-images.githubusercontent.com/46367351/54892565-f7506400-4eec-11e9-9af7-cef5fa6bc1da.png)

**On server:**
![image](https://user-images.githubusercontent.com/46367351/54892625-2d8de380-4eed-11e9-8bf0-109424aae9cb.png)

Tried to add the following polyfill code to display the **`Login`** page but cannot logging in at all.
1. Run `npm install --save @babel/polyfill`
2. Add `import "babel-polyfill";` to **index.js**
3. The **`Login`** page should be displayed now (with an exception that the button is not working).

**Comment by shahrul91** [comment]
Kindly test once deployed to Live Server.

**Comment by shahrul91** [comment]
Issue is no longer appear as it's already fixed.
