### ISSUE TITLE
Unable to take leave in different year

### ISSUE THREAD

**Issue by chaikp** [shahrul91/csileavemanagementsystem#188]
It should be a valid scenario where Employee apply leave in advance, or back dated leave application on different year

![image](https://user-images.githubusercontent.com/46370369/54899990-ab151c00-4f0c-11e9-95c3-0b642a061b12.png)

![image](https://user-images.githubusercontent.com/46370369/54899974-a18bb400-4f0c-11e9-80eb-11afd757a081.png)

**Comment by shahrul91** [comment]
I think this is fine right?

**Comment by shahrul91** [comment]
Closed. No fix required.
