### ISSUE TITLE
Add message "Recommended to use Chrome / Firefox"

### ISSUE THREAD

**Issue by chaikp** [shahrul91/csileavemanagementsystem#193]

**Comment by syazanajaafar** [comment]
Re-test and expected where message appeared in browsers other than Chrome and Firefox.
Hence, will close this issue.

**Internet Explorer:**

![Defect193_IE](https://user-images.githubusercontent.com/48428869/55302914-021f7180-5476-11e9-81a5-eac3244d2577.PNG)


**Chrome:**

![Defect193_Chrome](https://user-images.githubusercontent.com/48428869/55302921-09df1600-5476-11e9-8305-b6acd3895f5c.PNG)


**Firefox:**

![Defect193_Firefox](https://user-images.githubusercontent.com/48428869/55302925-0fd4f700-5476-11e9-8eed-2b59f077daa2.PNG)
