### ISSUE TITLE
No limit on number input fields (Leave Entitlements & Categories)

### ISSUE THREAD

**Issue by acapawn7** [shahrul91/csileavemanagementsystem#202]
**Module:**
HR Dashboard --> Leave Entitlements --> Add Entitlement
HR Dashboard --> Leave Entitlements --> Edit Entitlement
HR Dashboard --> Leave Categories --> Add Leave Category
HR Dashboard --> Leave Categories --> Edit Leave Category

**Issues:**
Currently HR is allowed to enter more than **2 digits** for number fields in **_Leave Entitlements_** without any error message. Meanwhile, inappropriate error message is displayed in **_Leave Categories_**.

**Expected:**
Should prevent HR from entering more than **2 digits** for these number fields.

**Screenshots:**
![image](https://user-images.githubusercontent.com/46367351/55463505-cd551b00-562b-11e9-93a6-aac6d3c0072b.png)

![image](https://user-images.githubusercontent.com/46367351/55463617-07262180-562c-11e9-81f0-1f387f3ed8cf.png)

![image](https://user-images.githubusercontent.com/46367351/55463660-1dcc7880-562c-11e9-9ace-1b42b5b5ec4f.png)

![image](https://user-images.githubusercontent.com/46367351/55463708-3177df00-562c-11e9-9f22-e36231ce6040.png)

**Comment by laichiun** [comment]
Retest PASS and updated as closed. 

**Add Entitlement**_ 
![image](https://user-images.githubusercontent.com/48428855/55848686-5f0ade00-5b80-11e9-8dc2-3cd30167c1e3.png)
![image](https://user-images.githubusercontent.com/48428855/55848710-75b13500-5b80-11e9-8dbc-cd8c43d3798e.png)
![image](https://user-images.githubusercontent.com/48428855/55848730-83ff5100-5b80-11e9-8e98-2479f08d8c45.png)
![image](https://user-images.githubusercontent.com/48428855/55848774-aa24f100-5b80-11e9-9900-ef06ad79eca3.png)

Edit Entitlement
![image](https://user-images.githubusercontent.com/48428855/55848806-c7f25600-5b80-11e9-9987-917159ef6035.png)
![image](https://user-images.githubusercontent.com/48428855/55848846-f708c780-5b80-11e9-9745-721d744e4a39.png)
![image](https://user-images.githubusercontent.com/48428855/55848863-0b4cc480-5b81-11e9-8e58-c5dc2305069e.png)

Add Leave Categories
![image](https://user-images.githubusercontent.com/48428855/55848919-44853480-5b81-11e9-8c74-656b005d0107.png)
![image](https://user-images.githubusercontent.com/48428855/55849032-c7a68a80-5b81-11e9-851a-570538f02c7f.png)
![image](https://user-images.githubusercontent.com/48428855/55849088-f6246580-5b81-11e9-8c89-f12d92f9bed3.png)
![image](https://user-images.githubusercontent.com/48428855/55849118-0b00f900-5b82-11e9-91e8-a539b5a80e44.png)
![image](https://user-images.githubusercontent.com/48428855/55849144-27049a80-5b82-11e9-8a44-05ffb86af876.png)

Edit Leave Category
![image](https://user-images.githubusercontent.com/48428855/55849200-574c3900-5b82-11e9-8228-e5a10311f768.png)
![image](https://user-images.githubusercontent.com/48428855/55849212-67641880-5b82-11e9-8f83-97304a3ac4e0.png)
![image](https://user-images.githubusercontent.com/48428855/55849230-75b23480-5b82-11e9-8031-978afc3eb616.png)
![image](https://user-images.githubusercontent.com/48428855/55849251-81056000-5b82-11e9-87af-4b9d43f46fc5.png)
