### ISSUE TITLE
No duplicate check when adding new records 

### ISSUE THREAD

**Issue by chaikp** [shahrul91/csileavemanagementsystem#204]
There's no duplicate check when adding new records on following modules. When a Key already exists in database, adding new record will overwrite the existing record.
- Leave Category
- Public Holiday
- Translate Item

**Comment by laichiun** [comment]
**Add Leave Category**
![image](https://user-images.githubusercontent.com/48428855/55849354-e0637000-5b82-11e9-9a3f-594aee06d441.png)
![image](https://user-images.githubusercontent.com/48428855/55849379-f709c700-5b82-11e9-8e9d-30b6a115361a.png)
![image](https://user-images.githubusercontent.com/48428855/55849560-a9418e80-5b83-11e9-8ad7-6dc69c6b95e6.png)

 Public Holiday
![image](https://user-images.githubusercontent.com/48428855/55849621-e574ef00-5b83-11e9-8e9b-a49aa6ee5d9f.png)
![image](https://user-images.githubusercontent.com/48428855/55849669-16552400-5b84-11e9-9949-60a4753431c5.png)
![image](https://user-images.githubusercontent.com/48428855/55849684-253bd680-5b84-11e9-9046-b91a19cfd6ee.png)

**Translate Item**
![image](https://user-images.githubusercontent.com/48428855/55849985-376a4480-5b85-11e9-9e51-0c457231a8f5.png)
![image](https://user-images.githubusercontent.com/48428855/55850028-549f1300-5b85-11e9-8269-52eec64d8fb9.png)
![image](https://user-images.githubusercontent.com/48428855/55850041-61bc0200-5b85-11e9-81ca-be6be1552e06.png)
![image](https://user-images.githubusercontent.com/48428855/55850065-700a1e00-5b85-11e9-8a52-a54f13d185a7.png)
![image](https://user-images.githubusercontent.com/48428855/55850100-90d27380-5b85-11e9-869c-5b289253eff0.png)
![image](https://user-images.githubusercontent.com/48428855/55850279-43a2d180-5b86-11e9-9957-eb3ba716fb57.png)
![image](https://user-images.githubusercontent.com/48428855/55850297-5917fb80-5b86-11e9-95b4-9819e83a192e.png)
